package com.dkbfactory.urlshortener.model;

import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;


 // Generates getters, setters, equals, hashCode, and toString

// Generates a no-args constructor
// For convenience when creating objects
@Entity
public class Url {
    @Id
    private String hash;

    private String originalUrl;

    // No-argument constructor (required by JPA)
    public Url() {}

    // Constructor with arguments
    public Url(String hash, String originalUrl) {
        this.hash = hash;
        this.originalUrl = originalUrl;
    }

    // Getters and setters (can be generated by your IDE)
    public String getHash() {
        return hash;
    }

    public void setHash(String hash) {
        this.hash = hash;
    }

    public String getOriginalUrl() {
        return originalUrl;
    }

    public void setOriginalUrl(String originalUrl) {
        this.originalUrl = originalUrl;
    }
}

